### ISSUE TITLE
催更

### ISSUE THREAD

**Issue by DaveBoy** [Reginer/MVVMHub#1]
写的很好，可惜等你写完的下一秒就是我的了
Ps:
1.buildSrc是干嘛的
2.common准备写啥，为什么是空白的

**Comment by Reginer** [comment]
buildSrc是gradle项目最先加载的部分
common假装有这么个东西，想写点啥我也没发现

**Comment by DaveBoy** [comment]
buildSrc是gradle项目最先加载的部分

这个是在哪设置的？我怎么没有搜索到

**Comment by Reginer** [comment]
不用配置，同名就可以了

**Comment by Reginer** [comment]
完结了
