### ISSUE TITLE
刚哥，我发现ViewState使用起来缺乏灵活性

### ISSUE THREAD

**Issue by DaveBoy** [Reginer/MVVMHub#4]
一般情况下是很方便，但是在某些情况下需要扩展，实际使用中感觉sealed写法缺乏扩展性。
一开始我的解决方案是：
另外再开一个，和网络请求的State独立开
![image](https://user-images.githubusercontent.com/16101638/71309245-a7350c80-2440-11ea-907c-e7d4741b0d16.png)

但是我发现某些情况下我需要合在网络请求的State里面一起通知activity：
比如我分页的时候我需要在返回数据的同时告诉Activity这是刷新的数据还是加载更多的数据（isRefresh），如果按照上面的独立开得方案，总觉得不太对劲,感觉会在某些情况下产生bug。

isRefresh类似的参数添加方式：
如果为了一个参数重新写一个通用的PageViewState感觉不划算，因为有很多相同部分，而且相关扩展也要对应写一份。
或者直接在原有的State上面加一个很多时候用不到的参数感觉也不是太舒服，如果之后还有其他的参数岂不是越加越多？

刚哥给点意见?

**Comment by Reginer** [comment]
![image](https://user-images.githubusercontent.com/12568257/71453296-80226600-27c5-11ea-8ccb-9ae7e93ce8ba.png)
onAppLoading回调也许会缺少提示，那个可以增加个提示参数。
至于判断是否是isRefresh这种，可以在<ViewState<Data’>>中的Entity里判断出来，其他的类似也是。是刷新还是加载更多，判断依据肯定会在对应的data里
